import './RecommendationCard.css';

export default function RecommendationCard({ recommendation }) {
  const items = Array.isArray(recommendation) ? recommendation : recommendation ? [recommendation] : [];

  if (items.length === 0) return null;

  return (
    <div className="card result-card">
      <div className="result-card__header">
        <span className="eyebrow">Recommendations</span>
      </div>
      <ul className="recommendation-list">
        {items.map((item, i) => (
          <li key={i} className="recommendation-list__item">
            <span className="recommendation-list__marker" aria-hidden="true" />
            {item}
          </li>
        ))}
      </ul>
      <p className="recommendation-note">
        Generated by the research prototype. Not a substitute for professional medical advice.
      </p>
    </div>
  );
}
