import Disclaimer from '../components/Disclaimer';
import Reveal from '../components/Reveal';
import './Methodology.css';

const PIPELINE = [
  { title: 'Preprocessing', desc: 'The uploaded image is resized, normalized, and prepared for the CNN input pipeline.' },
  { title: 'Fine-tuned ResNet50', desc: 'A ResNet50 backbone, fine-tuned on the project\u2019s dermatological image set, classifies the skin condition.' },
  { title: 'Classification + Grad-CAM + 256-D features', desc: 'Alongside the class prediction, Grad-CAM produces a visual explanation and a 256-dimensional feature vector is extracted from the network.' },
  { title: 'Environmental + stress inputs', desc: 'Temperature, humidity, UV index, AQI/PM2.5, and self-reported stress are collected as contextual variables.' },
  { title: 'Late fusion', desc: 'The 256-D image features are concatenated with the environmental variables into a single fused representation.' },
  { title: 'MLP severity regression', desc: 'A multilayer perceptron maps the fused representation to a continuous severity score.' },
  { title: 'Context tier', desc: 'The severity score is mapped to a Low / Medium / High tier.' },
  { title: 'Recommendations', desc: 'Tier- and condition-specific guidance is returned alongside the score.' },
];

export default function Methodology() {
  return (
    <section id="methodology" className="methodology">
      <div className="container">
        <Reveal as="div" className="section-heading">
          <span className="eyebrow">Methodology</span>
          <h2>How DermaIntel works</h2>
          <p>An end-to-end pipeline from raw image to a context-aware severity assessment.</p>
        </Reveal>

        <div className="methodology__pipeline">
          {PIPELINE.map((step, i) => (
            <Reveal as="div" key={step.title} delay={Math.min(i, 5) * 60} className="methodology__step">
              <span className="methodology__index mono">{String(i + 1).padStart(2, '0')}</span>
              <div>
                <h4>{step.title}</h4>
                <p>{step.desc}</p>
              </div>
            </Reveal>
          ))}
        </div>

        <div className="methodology__note">
          <Disclaimer>
            DermaIntel is a research prototype. Its severity scores and recommendations are
            generated by a learned model and have not undergone clinical validation. Always
            consult a qualified dermatologist for diagnosis or treatment decisions.
          </Disclaimer>
        </div>
      </div>
    </section>
  );
}
